---
driver:
  name: docker
platforms:
  - name: debian10
    image: timgrt/debian10-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: "/lib/systemd/systemd"
    pre_build_image: true
    exposed_ports:
      - 80/tcp
    published_ports:
      - 0.0.0.0:80:80/tcp
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
      stdout_callback: yaml
    ssh_connection:
      pipelining: false
  inventory:
    host_vars:
      all:
        ansible_user: ansible
